### ISSUE TITLE
Hello !

### ISSUE THREAD

**Issue by adrianmejiam** [jaris58/joox_dl#7]
you can modify to download Flac format    Thanks!

**Comment by jaris58** [comment]
btw why you need Flac Format ? M4A is better than Flac or MP3.
even is Flac better how to get better quality from poor quality, because joox only provide MP3 or M4A

**Comment by jaris58** [comment]
> you can modify to download Flac format Thanks!

sorry for confusing, you want me to provide a new format that is Flac format right?
if so, for what purpose?
whether to improve the quality?
or just to change my format regardless of the quality?
because if i format m4a or mp3 to Flac it doesn't fix the lost quality.
because Joox only provides 2 file formats namely m4a and mp3 each format has a high quality file (optional)
